export enum ProjectTypeEnum {
  ECommerce = "e-commerce-logistics",
  HealthTech = "healthcare-healthtech",
  EdTech = "education-edtech",
  Hospitality = "services-hospitality",
  Entertainment = "entertainment-media",
  AiMl = "ai-ml",
  Engineering = "engineering-research",
}

export enum ProjectNameEnum {
  CNHI_PROJECTS = "Council of National Health Insurance (CNHI) Projects",
  DIGITAL_TWIN = "Digital Twin (Sehaty)",
  CAPACITY_DEMAND = "Capacity and Demand",
  OPEN_DATA = "Open Data",
  RZERVE = "Rzerve",
  MASROOF = "Masroof",
  KT_MESSENGER = "KT Messenger (Kalam Time)",
  CORNERS = "Corners",
  AT_HOME_DOC = "At Home Doc",
  MACQUEEN = "MacQueen",
  GEBHALY = "Gebhaly",
  EG_PARCEL_EXPRESS = "EG Parcel Express - EPX",
  LOOK_ME_UP = "Look me up",
  IZI_HANDMADE = "IzI Handmade",
  EGY_SCHOOLS = "EgySchools",
  SPOTIFY_CLONE = "Spotify Clone",
  SANTA_GAME = "Santa Game",
  GRADES_AUTOFILLER = "Grades Autofiller",
  HARVARD_PROCESSOR = "Harvard Processor",
  FONT_CLASSIFIER = "Font Classifier",
  SRP = "SRP",
}

export enum TechEnum {
  React = "React",
  ReactNative = "React Native",
  Expo = "Expo",
  NextJS = "Next.js",
  NestJS = "NestJS",
  Typescript = "Typescript",
  JavaScript = "Javascript",
  NodeJS = "Node.js",
  Docker = "Docker",
  AI = "AI Tools",
  Flutter = "Flutter",
  Vue = "Vue.js",
  Nuxt = "Nuxt.js",
  GraphQl = "GraphQl",
  SurrealDB = "SurrealDB",
  SpringBoot = "Spring Boot",
  MongoDB = "MongoDB",
  Express = "Express",
  Firebase = "Firebase",
  OpenGL = "OpenGL",
  Cpp = "C++",
  Python = "Python",
  OpenCV = "OpenCV",
  Flask = "Flask",
  VHDL = "VHDL",
  ScikitLearn = "Scikit-learn",
  Omnetpp = "omnet++",
  DotNet = ".NET",
  HTML = "HTML",
  CSS_SASS = "CSS/Sass",
  SQL = "SQL",
  SQLServer = "SQL Server",
  OOP = "OOP",
  CI_CD = "CI/CD",
  Git = "Git",
}

export enum WorkTypeEnum {
  Remote = "remote",
  OnSite = "on-site",
  Hybrid = "hybrid",
  RemoteContract = "remote, contract",
}

export enum GeminiApiErrorCode {
  MISSING_FIELDS = "MISSING_FIELDS",
  API_KEY_NOT_CONFIGURED = "API_KEY_NOT_CONFIGURED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  GEMINI_QUOTA_EXCEEDED = "GEMINI_QUOTA_EXCEEDED",
  EMPTY_RESPONSE = "EMPTY_RESPONSE",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
