#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const PROJECT_ROOT = path.resolve(__dirname, "..");
const SVG_FOLDER = path.join(PROJECT_ROOT, "src/assets/icons/svg");
const OUTPUT_FILE = path.join(PROJECT_ROOT, "src/assets/icons/index.ts");
const REACT_SUFFIX = "";
const SVG_RELATIVE_FOLDER = "./svg";

// Flag to prevent infinite loops
const LOCK_FILE = path.join(__dirname, ".update-icons.lock");

/**
 * Convert kebab-case filename to PascalCase icon name
 * Examples:
 * - 'home.svg' -> 'HomeIcon'
 * - 'presentation-chart.svg' -> 'PresentationChartIcon'
 * - 'user-profile.svg' -> 'UserProfileIcon'
 */
function fileNameToIconName(fileName) {
  const nameWithoutExt = fileName.replace(/\.svg$/, "");

  return (
    nameWithoutExt
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join("") + "Icon"
  );
}

/**
 * Generate export statement for an SVG file
 */
function generateExport(fileName) {
  const iconName = fileNameToIconName(fileName);
  return `export { default as ${iconName} } from "${SVG_RELATIVE_FOLDER}/${fileName}${REACT_SUFFIX}";`;
}

/**
 * Check if we're in a potential infinite loop
 */
function shouldSkipUpdate() {
  // Check if lock file exists and is recent (within last 2 seconds)
  if (fs.existsSync(LOCK_FILE)) {
    const lockStats = fs.statSync(LOCK_FILE);
    const lockAge = Date.now() - lockStats.mtimeMs;

    if (lockAge < 2000) {
      // 2 seconds
      console.log("🔒 Skipping update to prevent infinite loop");
      return true;
    } else {
      // Remove stale lock file
      fs.unlinkSync(LOCK_FILE);
    }
  }

  return false;
}

/**
 * Create lock file to prevent infinite loops
 */
function createLockFile() {
  fs.writeFileSync(LOCK_FILE, Date.now().toString());
}

/**
 * Remove lock file
 */
function removeLockFile() {
  if (fs.existsSync(LOCK_FILE)) {
    fs.unlinkSync(LOCK_FILE);
  }
}

/**
 * Main function to update the icons file
 */
function updateIcons() {
  try {
    // Check if we should skip this update to prevent infinite loops
    if (shouldSkipUpdate()) {
      return;
    }

    // Create lock file
    createLockFile();

    // Check if SVG folder exists
    if (!fs.existsSync(SVG_FOLDER)) {
      console.error(`❌ SVG folder '${SVG_FOLDER}' does not exist`);
      removeLockFile();
      process.exit(1);
    }

    // Read all files in the SVG folder
    const files = fs.readdirSync(SVG_FOLDER);
    console.log(`🔍 Found ${files.length} files in the SVG folder`);

    // Filter for SVG files only
    const svgFiles = files.filter((file) => file.endsWith(".svg")).sort(); // Sort alphabetically for consistent output

    if (svgFiles.length === 0) {
      console.warn("⚠️  No SVG files found in the SVG folder");
      removeLockFile();
      return;
    }

    // Generate export statements
    const exports = svgFiles.map(generateExport);

    // Create the content with header comment
    const content = [
      "// Auto-generated file - Do not edit manually",
      "// This file is updated automatically by the update-icons script",
      "// Last updated: " + new Date().toISOString(),
      "",
      ...exports,
      "", // Empty line at the end
    ].join("\n");

    // Check if content has actually changed to avoid unnecessary writes
    let existingContent = "";
    let shouldWrite = true;
    let wasAutoGenerated = true;

    if (fs.existsSync(OUTPUT_FILE)) {
      existingContent = fs.readFileSync(OUTPUT_FILE, "utf8");
      wasAutoGenerated = existingContent.includes(
        "// Auto-generated file - Do not edit manually"
      );

      // Only write if content has changed (ignoring timestamp)
      const existingWithoutTimestamp = existingContent.replace(
        /\/\/ Last updated: .*\n/,
        ""
      );
      const newWithoutTimestamp = content.replace(
        /\/\/ Last updated: .*\n/,
        ""
      );

      shouldWrite = existingWithoutTimestamp !== newWithoutTimestamp;
    }

    if (shouldWrite) {
      // Write to output file
      fs.writeFileSync(OUTPUT_FILE, content, "utf8");

      // Determine trigger reason
      const triggerReason = wasAutoGenerated
        ? "SVG files changed"
        : "Manual edit detected - restoring auto-generated content";

      // Log success
      console.log(`✅ Icons file updated successfully! (${triggerReason})`);
      console.log(`📁 Found ${svgFiles.length} SVG files:`);
      svgFiles.forEach((file) => {
        const iconName = fileNameToIconName(file);
        console.log(`   ${file} → ${iconName}`);
      });
      console.log(`📝 Updated ${OUTPUT_FILE}`);

      if (!wasAutoGenerated && existingContent) {
        console.log(
          "⚠️  Note: Manual changes to index.ts were overwritten to maintain consistency"
        );
      }
    } else {
      console.log("📄 No changes detected - file already up to date");
    }

    // Remove lock file after a short delay
    setTimeout(() => {
      removeLockFile();
    }, 1000);
  } catch (error) {
    console.error("❌ Error updating icons:", error.message);
    removeLockFile();
    process.exit(1);
  }
}

// Handle command line arguments
const args = process.argv.slice(2);
if (args.includes("--help") || args.includes("-h")) {
  console.log(`
Icon Update Script
==================

Updates the icon exports file based on SVG files in the ${SVG_FOLDER} folder.

Usage:
  node update-icons.js

Options:
  --help, -h    Show this help message

Configuration:
  SVG_FOLDER: ${SVG_FOLDER}
  OUTPUT_FILE: ${OUTPUT_FILE}
  
The script will:
1. Scan the ${SVG_FOLDER} folder for .svg files
2. Generate PascalCase icon names (e.g., home.svg → HomeIcon)
3. Update ${OUTPUT_FILE} with export statements
4. Skip updates if content hasn't changed to prevent infinite loops
5. Detect and restore manual edits to maintain consistency
  `);
  process.exit(0);
}

// Run the script
updateIcons();
